

# Introduction

**Purpose**

Wine is an alcoholic beverage made from fermented grape juice. Generally, a wine's quality is determined by taste, smell, and visual tests performed by wine experts, sommeliers. These tests grade the wine on subjective measures: Acidity, Sweetness, Alcohol, Tannin and Aroma. @wine_exactly_web Though these evaluations are subjective, there is an overlap between these subjective characteristics and a wines physicochemical properties. For example, a wines perceived acidity or tartness can be related to the pH of the wine and a wines perceived sweetness can be related to the residual sugar of the wine.

The goal of our research is to determine:

Can we determine an accurate subjective rating of a wine based solely on its physicochemical properties?

***Why is this important?***

An accurate predictive model for determining the quality of wine will enable small wineries and vineyards, especially those from less established wine regions, to more accurately price their inventory and ensure a better return on investment.

**Statistical or Analytical Method**

We will be using the the following statistical methods to create predictive models for quality of wine:

- Random Forest
- K-Nearest Neighbor
- Elastic Net Regression (LASSO and Ridge)

\pagebreak
\tableofcontents
  
